= u2ug: UUID to Ubisoft
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]

image:https://github.com/ncomet/u2ug/actions/workflows/go.yml/badge.svg[Go,link=https://github.com/ncomet/u2ug/actions/workflows/go.yml]

A Golang library that given a https://fr.wikipedia.org/wiki/Universally_unique_identifier[UUID] (v1 or v4), will return the concatenation of a random adjective and Ubisoft game, or character.

[quote]
c840005c-06f0-43af-a96f-77bf13fdc956 -> Crazy Rocksmith

== Disclaimer

IMPORTANT: Highly inspired by https://github.com/CleverCloud/uuid_to_pokemon.rs, but in Go. Special thanks to the https://www.clever-cloud.com/[Clever Cloud] teams ;)

It is an https://en.wikipedia.org/wiki/Injective_function[_injective function_], meaning that a given UUID will *always produce the same name*, but a given name could be the output of two different UUIDs.

It does should not matter since the original UUID must be kept as original source of uniqueness. This library is created in order to assign a reproducible human-readable name to a UUID.

== How to use

=== Go library

[source,bash]
----
go get github.com/ncomet/u2ug/ubi
----

[source,go]
----
import "github.com/ncomet/u2ug/ubi"

game, err := ubi.Game("d3acc428-3172-457a-9447-6a22263ef6b3")
if err != nil {
	panic(err)
}

fmt.Println(game) // "Selfish Space Junkies"

character, err := ubi.Character("d3acc428-3172-457a-9447-6a22263ef6b3")
if err != nil {
	panic(err)
}

fmt.Println(character) // "Selfish Selena"
----

=== Binary

[source,bash]
----
$ go build .
$ ./u2ug game d3acc428-3172-457a-9447-6a22263ef6b3
Selfish Space Junkies
$ ./u2ug character d3acc428-3172-457a-9447-6a22263ef6b3
Selfish Selena
----


[source,bash]
----
$ go run ./ game d3acc428-3172-457a-9447-6a22263ef6b3
Selfish Space Junkies
$ go run ./ character d3acc428-3172-457a-9447-6a22263ef6b3
Selfish Selena
----

=== Docker

[source,bash]
----
$ docker build -t u2ug .
$ docker run u2ug game d3acc428-3172-457a-9447-6a22263ef6b3
Selfish Space Junkies
----

== Some examples

=== Games
|===
|Polite Tom Clancy's Ghost Recon Advanced Warfighter
|Dreadful Gunfighter II: Revenge of Jesse James
|Shrill Cloudy with a Chance of Meatballs
|Shrill Rocket: Robot on Wheels
|Meek Assassin's Creed Origins
|Caring Far Cry New Dawn
|Scared Buck Bumble
|Selfish Splinter Cell: Blacklist - Spider-Bot
|Shining Petz: Bunnyz
|Angry Seven Kingdoms II: The Fryhtan Wars
|Odd ZombiU
|Plush Super Bust-A-Move
|Sleepy Tiger Woods PGA Tour Golf
|Foul Adventures in Music with the Recorder
|Cruel Heroes of Might and Magic V: Tribes of the East
|Stingy Theocracy
|Quiet Lost: Via Domus
|Bored Skateball
|Tiny Warlords: Battlecry II
|Shining Imagine: Babyz
|Rich All Star Tennis '99
|===

=== Characters

|===
|Soaring Tus
|Fussy Eivor
|Thrifty Amaru
|Afraid Barr-Barr
|Chilly Mo
|Creeping Thant
|Sloppy Teen Punk
|Caring Nikolai Andreievich Orelov
|Stingy Princess
|Generous Hytham
|Rapid Glaz
|Grimy Sigurd
|Cowardly Straker
|Bashful Tiva
|Generous Amaru
|Kind Clancy
|Hard Piquedram
|===
== Games list source

All games were taken and de-duplicated from:

https://en.wikipedia.org/wiki/List_of_Ubisoft_games

== Characters list source

Extracted from various dedicated game wiki fandom websites.