package ubi

var games = []string{
	"187: Ride or Die",
	"ABBA: You Can Dance",
	"Academy of Champions: Soccer",
	"Action Euro Soccer 96",
	"Action Soccer",
	"Advance Guardian Heroes",
	"Adventures in Music with the Recorder",
	"AGOS: A Game of Space",
	"Alex Builds His Farm",
	"Alex Ferguson's Player Manager 2001",
	"Alexander",
	"All Star Tennis 2000",
	"All Star Tennis '99",
	"Amazing Learning Games with Rayman",
	"America's Army: Rise of a Soldier",
	"America's Army: True Soldiers",
	"AND 1 Streetball",
	"Animal Genius",
	"Animorphs",
	"Anne McCaffrey's Freedom: First Resistance",
	"Anno 1404",
	"Anno 1701: Dawn of Discovery",
	"Anno 1800",
	"Anno 2070",
	"Anno 2205",
	"Anno 2205: Asteroid Miner",
	"Anno Online",
	"Anno: Build an Empire",
	"Ape Escape 2",
	"Ape Escape: Pumped & Primed",
	"Arcatera: The Dark Brotherhood",
	"Armored Core 2",
	"Armored Core: For Answer",
	"Arthur and the Revenge of Maltazard",
	"Asphalt",
	"Asphalt 6: Adrenaline",
	"Asphalt: Injection",
	"Asphalt: Urban GT",
	"Asphalt: Urban GT 2",
	"Assassin's Creed",
	"Assassin's Creed Chronicles: China",
	"Assassin's Creed Chronicles: India",
	"Assassin's Creed Chronicles: Russia",
	"Assassin's Creed Identity",
	"Assassin's Creed II",
	"Assassin's Creed II: Discovery",
	"Assassin's Creed III",
	"Assassin's Creed III Remastered",
	"Assassin's Creed III: Liberation",
	"Assassin's Creed Infinity",
	"Assassin's Creed IV: Black Flag",
	"Assassin's Creed Odyssey",
	"Assassin's Creed Origins",
	"Assassin's Creed Pirates",
	"Assassin's Creed Rogue",
	"Assassin's Creed Rogue Remastered",
	"Assassin's Creed Syndicate",
	"Assassin's Creed Unity",
	"Assassin's Creed Valhalla",
	"Assassin's Creed: Altaïr's Chronicles",
	"Assassin's Creed: Bloodlines",
	"Assassin's Creed: Brotherhood",
	"Assassin's Creed: Liberation HD",
	"Assassin's Creed: Memories",
	"Assassin's Creed: Rebellion",
	"Assassin's Creed: Recollection",
	"Assassin's Creed: Revelations",
	"Assassin's Creed: The Ezio Collection",
	"Assassin's Creed: The Rebel Collection",
	"Astonishia Story",
	"Atomega",
	"Avatar: Frontiers of Pandora",
	"B.A.T.",
	"Babel Rising",
	"Babel Rising 3D",
	"Baby Life",
	"Baldur's Gate: Dark Alliance",
	"Batman Beyond: Return of the Joker",
	"Batman: Chaos in Gotham",
	"Batman: Gotham City Racer",
	"Batman: Rise of Sin Tzu",
	"Batman: Vengeance",
	"Battle of Giants: Dinosaurs",
	"Battle of Giants: Dinosaurs - Fight for Survival",
	"Battle of Giants: Dinosaurs Strike",
	"Battle of Giants: Dragons",
	"Battle of Giants: Dragons - Bronze Edition",
	"Battle of Giants: Mutant Insects",
	"Battle of Giants: Mutant Insects - Revenge",
	"Battle Realms",
	"Battles of Prince of Persia",
	"Battleship",
	"Beowulf: The Game",
	"Beyond Divinity",
	"Beyond Good & Evil",
	"Beyond Good & Evil HD",
	"Beyond Good and Evil 2",
	"Biathlon 2004",
	"Biathlon 2005",
	"Biathlon 2006: Go for Gold",
	"Blazing Angels 2: Secret Missions of WWII",
	"Blazing Angels: Squadrons of WWII",
	"Bloody Good Time",
	"Boggle",
	"Bomberman",
	"Bomberman Hardball",
	"Boot Camp Academy",
	"Brain Blasters",
	"Brain Spa",
	"Bratz",
	"Brawlhalla",
	"Breath of Fire",
	"Breath of Fire II",
	"Broken Sword: Shadow of the Templars - The Director's Cut",
	"Brothers in Arms DS",
	"Brothers in Arms: D-Day",
	"Brothers in Arms: Double Time",
	"Brothers in Arms: Earned in Blood",
	"Brothers in Arms: Hell's Highway",
	"Brothers in Arms: Road to Hill 30",
	"Buck Bumble",
	"Business Tycoon",
	"C.O.P.: The Recruit",
	"Call of Cthulhu: Dark Corners of the Earth",
	"Call of Juarez",
	"Call of Juarez: Bound in Blood",
	"Call of Juarez: Gunslinger",
	"Call of Juarez: The Cartel",
	"Care Bears: Belly Match",
	"Carl Lewis Athletics 2000",
	"Castle & Co",
	"Catz",
	"Catz 5",
	"CellFactor: Psychokinetic Wars",
	"Celtic Legends",
	"Cesar Millan's Dog Whisperer",
	"Champions of Anteria",
	"Champions of Norrath",
	"Champions: Return to Arms",
	"Championship Manager",
	"Charlie's Angels",
	"Chessmaster",
	"Chessmaster 10th Edition",
	"Chessmaster 8000",
	"Chessmaster 9000",
	"Chessmaster Live",
	"Chessmaster: Grandmaster Edition",
	"Chessmaster: The Art of Learning",
	"Child of Eden",
	"Child of Light",
	"Child of Light: Ultimate Edition",
	"Circus Games",
	"City of Love: Paris",
	"Clash of Beasts",
	"Cloudberry Kingdom",
	"Cloudy with a Chance of Meatballs",
	"Cob to the Rescue!",
	"Cold Fear",
	"Colin McRae Rally 2.0",
	"Combat of Giants: Dinosaurs 3D",
	"Conflict Zone",
	"Conquest: Frontier Wars",
	"Cook Wars",
	"Cosmic Family",
	"Cover Girl",
	"Cranium Kabookii",
	"Crouching Tiger, Hidden Dragon",
	"CSI: 3 Dimensions of Murder",
	"CSI: Crime Scene Investigation",
	"CSI: Dark Motives",
	"CSI: Deadly Intent",
	"CSI: Fatal Conspiracy",
	"CSI: Hard Evidence",
	"CSI: Hidden Crimes",
	"CSI: Miami",
	"CSI: NY - The Game",
	"CSI: Unsolved!",
	"Cubic Ninja",
	"Curling 2006",
	"Dance on Broadway",
	"Dark Messiah of Might and Magic",
	"Dark Messiah: Might and Magic - Elements",
	"Dark Planet: Battle for Natrolis",
	"Darkwatch",
	"David O'Leary's Total Soccer 2000",
	"Deathrow",
	"Deep Fighter",
	"Defender of the Crown",
	"Destroyer Command",
	"Devil May Cry 3: Dante's Awakening - Special Edition",
	"Discovery Tour: Assassin's Creed - Ancient Egypt",
	"Discovery Tour: Assassin's Creed - Ancient Greece",
	"Discovery Tour: Viking Age",
	"Disney's Aladdin",
	"Disney's Dinosaur",
	"Disney's Donald Duck: Goin' Quackers",
	"Disney's PK: Out of the Shadows",
	"Disney's Tarzan Untamed",
	"Disney's The Emperor's New Groove",
	"Disney's Treasure Planet",
	"Disney's Winnie the Pooh's Rumbly Tumbly Adventure",
	"Dogz",
	"Dogz 5",
	"Dokapon: Monster Hunter",
	"Donald Duck Advance",
	"Downtown Run",
	"Dragon Riders: Chronicles of Pern",
	"Dragon's Lair 3D: Return to the Lair",
	"Drakengard 2",
	"Driver 76",
	"Driver: Parallel Lines",
	"Driver: Renegade",
	"Driver: San Francisco",
	"Driver: Speedboat Paradise",
	"Dungeon Hunter: Alliance",
	"E.T. The Extra-Terrestrial: Away From Home",
	"E.T. The Extra-Terrestrial: Interplanetary Mission",
	"E.T.: Phone Home Adventure",
	"Eagle Flight",
	"Earth 2140",
	"Echelon",
	"Emergency Heroes",
	"Enchanted Arms",
	"Ener-G: Dance Squad",
	"Escape from Monkey Island",
	"ESPN Sports Connection",
	"Eternal Ring",
	"Eurofighter Typhoon",
	"Europa Universalis",
	"Europa Universalis II",
	"Evil Twin: Cyprien's Chronicles",
	"Evolution 2: Far off Promise",
	"Evolution Worlds",
	"Evolution: The World of Sacred Device",
	"Exit",
	"F1 Pole Position",
	"F1 Pole Position 2",
	"F1 Pole Position 64",
	"F1 Racing Championship",
	"F1 Racing Simulation",
	"Face Up: The Selfie Game",
	"Faces of War",
	"Fairyland: Melody Magic",
	"Family Fest Presents Movie Games",
	"Family Feud",
	"Family Feud: 2010 Edition",
	"Family Feud: 2012 Edition",
	"Family Feud: Decades",
	"Far Cry",
	"Far Cry 2",
	"Far Cry 3",
	"Far Cry 3: Blood Dragon",
	"Far Cry 3: Classic Edition",
	"Far Cry 4",
	"Far Cry 4: Arcade Poker",
	"Far Cry 4: Arena Master",
	"Far Cry 5",
	"Far Cry 6",
	"Far Cry Classic",
	"Far Cry Instincts",
	"Far Cry New Dawn",
	"Far Cry Primal",
	"Far Cry Vengeance",
	"Far Cry: Instincts - Evolution",
	"Far Cry: Instincts - Predator",
	"Fashion Studio Paris Collection",
	"Fatal Frame II: Crimson Butterfly",
	"Fighter Within",
	"Fighters Uncaged",
	"Final Command",
	"Final Fight",
	"First Samurai",
	"Fit in Six",
	"Flashback",
	"Flipper & Lopaka",
	"FLOW: Urban Dance Uprising",
	"Football World Manager",
	"For Honor",
	"Frantix",
	"Fred",
	"From Dust",
	"Funky Barn 3D",
	"Gadget Tycoon",
	"Galaxy Racers",
	"Gex: Enter the Gecko",
	"Globetrotter 2",
	"Go! Sudoku",
	"Gold and Glory: The Road to El Dorado",
	"Gold's Gym Dance Workout",
	"Gourmet Chef",
	"Grandia",
	"Grandia II",
	"Gravity Falls: Legend of the Gnome Gemulets",
	"Great Courts 2",
	"Grey's Anatomy: The Video Game",
	"GripShift",
	"Grow Home",
	"Grow Up",
	"Growtopia",
	"GT Pro Series",
	"Guitar Rock Tour",
	"Gunfighter II: Revenge of Jesse James",
	"Gunfighter: The Legend of Jesse James",
	"Happy Cooking",
	"Harvest Moon: A Wonderful Life",
	"Haze",
	"Hell-Copter",
	"Hell's Kitchen: The Game",
	"Heritage of Kings: The Settlers",
	"Heroes of Might and Magic V",
	"Heroes of Might and Magic V: Tribes of the East",
	"Heroes of the Pacific",
	"Heroes Over Europe",
	"Hexcite: The Shapes of Victory",
	"Hexsider",
	"Hooters Road Trip",
	"Horse Haven: World Adventures",
	"Horses 3D",
	"Horsez",
	"Hungry Dragon",
	"Hungry Shark: World",
	"Hype: The Time Quest",
	"Hyper Scape",
	"Hyper V-Ball",
	"I Am Alive",
	"Idle Restaurant Tycoon",
	"IL-2 Sturmovik",
	"IL-2 Sturmovik: Cliffs of Dover",
	"IL-2 Sturmovik: Forgotten Battles",
	"Ilyad",
	"Imagine: Animal Doctor",
	"Imagine: Artist",
	"Imagine: Babysitters",
	"Imagine: Babyz",
	"Imagine: Babyz Fashion",
	"Imagine: Ballet Star",
	"Imagine: Boutique Owner",
	"Imagine: Champion Rider",
	"Imagine: Cheerleader",
	"Imagine: Detective",
	"Imagine: Family Doctor",
	"Imagine: Fashion Designer",
	"Imagine: Fashion Designer - New York",
	"Imagine: Fashion Designer - World Tour",
	"Imagine: Fashion Life",
	"Imagine: Fashion Party",
	"Imagine: Figure Skater",
	"Imagine: Gymnast",
	"Imagine: Ice Champions",
	"Imagine: Interior Designer",
	"Imagine: Journalist",
	"Imagine: Makeup Artist",
	"Imagine: Master Chef",
	"Imagine: Movie Star",
	"Imagine: Music Fest",
	"Imagine: My Restaurant",
	"Imagine: Party Babyz",
	"Imagine: Party Planner",
	"Imagine: Rock Star",
	"Imagine: Salon Stylist",
	"Imagine: Soccer Captain",
	"Imagine: Sweet 16",
	"Imagine: Teacher",
	"Imagine: Teacher - Class Trip",
	"Imagine: Wedding Designer",
	"Imagine: Zookeeper",
	"Immortals Fenyx Rising",
	"Import Tuner Challenge",
	"In Cold Blood",
	"In Memoriam",
	"Indiana Jones and the Last Crusade: The Action Game",
	"Infestation",
	"Inspector Gadget: Gadget's Crazy Maze",
	"Inspector Gadget: Operation Madkactus",
	"Intruder",
	"Iron Lord",
	"Jade Cocoon 2",
	"Jake Power: Fireman",
	"Jake Power: Policeman",
	"Jam Sessions",
	"Jam Sessions 2",
	"James Cameron's Avatar: The Game",
	"James Noir's Hollywood Crimes",
	"Jeopardy!",
	"Jet Ion GP",
	"Jim Henson's Bear in the Big Blue House",
	"Jimmy Connors Pro Tennis Tour",
	"Jimmy Connors Tennis",
	"Jojo's Fashion Show: Design in a Dash!",
	"Jupiter's Masterdrive",
	"Just Dance",
	"Just Dance 2",
	"Just Dance 2014",
	"Just Dance 2015",
	"Just Dance 2016",
	"Just Dance 2017",
	"Just Dance 2018",
	"Just Dance 2019",
	"Just Dance 2020",
	"Just Dance 2021",
	"Just Dance 2022",
	"Just Dance 3",
	"Just Dance 4",
	"Just Dance Kids",
	"Just Dance Kids 2",
	"Just Dance Kids 2014",
	"Just Dance Now",
	"Just Dance: Best Of",
	"Just Dance: Disney Party",
	"Just Dance: Disney Party 2",
	"Just Dance: Greatest Hits",
	"Just Dance: Summer Party",
	"Just Sing",
	"King Kong: The Official Game of the Movie",
	"Kiyeko and the Lost Night",
	"Knockout Party",
	"Kohan: Immortal Sovereigns",
	"Kong: The 8th Wonder of the World",
	"Largo Winch .// Commando SAR",
	"Largo Winch: Empire Under Threat",
	"Laura's Happy Adventures",
	"Le Maître des Âmes",
	"Le Nécromancien",
	"Legendary Fishing",
	"Little Nicky",
	"Little Raiders: Robin's Revenge",
	"Lock On: Modern Air Combat",
	"Lost: Via Domus",
	"LostMagic",
	"Lumines: Electronic Symphony",
	"Lumines: Puzzle Fusion",
	"Lunar Legend",
	"Lunar: Dragon Song",
	"Mad Riders",
	"Mange Cailloux",
	"Marathon Manager",
	"Mario + Rabbids Kingdom Battle",
	"Mario + Rabbids Sparks of Hope",
	"Maths and English with Rayman: Volume 2",
	"Maths and English with Rayman: Volume 3",
	"Maupiti Island",
	"Mega Man Battle Network",
	"Mega Man Battle Network 2",
	"Mega-Lo-Mania",
	"Metropolis Crimes",
	"Miami Nights: Singles in the City",
	"Michael Jackson: The Experience",
	"Michael Jackson: The Experience 3D",
	"Might & Magic Heroes VI",
	"Might & Magic Heroes: Era of Chaos",
	"Might & Magic X: Legacy",
	"Might & Magic: Chess Royale",
	"Might & Magic: Clash of Heroes",
	"Might & Magic: Duel of Champions",
	"Might & Magic: Heroes Online",
	"Might and Magic VI: The Mandate of Heaven",
	"Mike Tyson Boxing",
	"Mind Quiz",
	"Mind Quiz: Your Brain Coach",
	"Mobil 1 Rally Championship",
	"Moderngroove: Ministry of Sound Edition",
	"Monaco Grand Prix Racing Simulation 2",
	"Monkey King Escape",
	"Monopoly",
	"Monopoly Deal",
	"Monopoly Madness",
	"Monopoly Plus",
	"Monster 4x4 3D",
	"Monster 4x4 Stunt Racer",
	"Monster 4x4: Masters of Metal",
	"Monster 4x4: World Circuit",
	"Monster Jam: Maximum Destruction",
	"Moorhen 3 ...Chicken Chase",
	"MotionSports",
	"MotionSports Adrenaline",
	"Moto Racer Advance",
	"MotoHeroz",
	"Mucha Lucha! Mascaritas of the Lost Code",
	"Muppet Pinball Mayhem",
	"Murakumo: Renegade Mech Pursuit",
	"My Chinese Coach",
	"My Fitness Coach",
	"My French Coach",
	"My Fun Facts Coach",
	"My Japanese Coach",
	"My SAT Coach",
	"My Secret World by Imagine",
	"My Spanish Coach",
	"My Stop Smoking Coach: Allen Carr's EasyWay",
	"My Weight Loss Coach",
	"My Word Coach",
	"Myst III: Exile",
	"Myst IV: Revelation",
	"Myst V: End of Ages",
	"Naruto: Rise of a Ninja",
	"Naruto: The Broken Bond",
	"NCIS",
	"NCIS 3D",
	"NCIS: Hidden Crimes",
	"NewU: Fitness First Personal Trainer",
	"Night Hunter",
	"Nitrobike",
	"No More Heroes",
	"No More Heroes 2: Desperate Struggle",
	"Nutty Fluffies Rollercoaster",
	"OddBallers",
	"Ode",
	"OK! Puzzle Stars",
	"O'Leary Manager 2000",
	"Open Season",
	"Othello Killer",
	"Outland",
	"Over G Fighters",
	"Pacific Fighters",
	"Panzer General Online",
	"Panzer General: Allied Assault",
	"Papyrus",
	"Papyrus: Le Secret de la Cité Perdue",
	"Paradise",
	"Payuta and the Ice God",
	"Pearl Harbor: Strike at Dawn",
	"Petz Beach",
	"Petz Countryside",
	"Petz Dolphinz Encounter",
	"Petz Fantasy 3D",
	"Petz Fashion: Dogz and Catz",
	"Petz Hamsterz Family",
	"Petz Nursery",
	"Petz Rescue: Endangered Paradise",
	"Petz Rescue: Ocean Patrol",
	"Petz Rescue: Wildlife Vet",
	"Petz Sports",
	"Petz Wild Animals: Dolphinz",
	"Petz: Bunnyz",
	"Petz: Catz 2",
	"Petz: Catz Clan",
	"Petz: Catz Family",
	"Petz: Crazy Monkeyz",
	"Petz: Dogz 2",
	"Petz: Dogz Family",
	"Petz: Dogz Talent Show",
	"Petz: Hamsterz 2",
	"Petz: Hamsterz Superstarz",
	"Petz: Horse Club",
	"Petz: Horseshoe Ranch",
	"Petz: Horsez 2",
	"Petz: Monkeyz House",
	"Petz: Pony Beauty Pageant",
	"Petz: Wild Animals - Tigerz",
	"Pick 'n Pile",
	"Pippa Funnell: Take the Reins",
	"Pippa Funnell: The Golden Stirrup Challenge",
	"Pippa Funnell: The Stud Farm Inheritance",
	"Pirates of the Caribbean: The Legend of Jack Sparrow",
	"Planet of the Apes",
	"Platinum Sudoku",
	"Playboy: The Mansion",
	"POD",
	"POD SpeedZone",
	"POD: Back to Hell",
	"Pool of Radiance",
	"Pool of Radiance: Ruins of Myth Drannor",
	"Poptropica Adventures",
	"PowerUp Heroes",
	"Prince of Persia",
	"Prince of Persia Classic",
	"Prince of Persia: Revelations",
	"Prince of Persia: Rival Swords",
	"Prince of Persia: The Fallen King",
	"Prince of Persia: The Forgotten Sands",
	"Prince of Persia: The Sands of Time",
	"Prince of Persia: The Sands of Time HD",
	"Prince of Persia: The Sands of Time Remake",
	"Prince of Persia: The Shadow and the Flame",
	"Prince of Persia: The Two Thrones",
	"Prince of Persia: The Two Thrones HD",
	"Prince of Persia: Warrior Within",
	"Prince of Persia: Warrior Within HD",
	"Princesse Sissi et Tempête",
	"Pro Pinball: Timeshock!",
	"Pro Rally",
	"Pro Rally 2001",
	"Pro Rally 2002",
	"Protöthea",
	"Puffy's Saga",
	"Puppies 3D",
	"Puppy Palace",
	"Puzzler Mind Gym 3D",
	"Puzzler World 2011",
	"Puzzler World 2012",
	"Quick Yoga Training",
	"R.U.S.E.",
	"Rabbids Appisodes",
	"Rabbids Big Bang",
	"Rabbids Crazy Rush",
	"Rabbids Go Home",
	"Rabbids Go Home: A Comedy Adventure",
	"Rabbids Invasion: The Interactive TV Show",
	"Rabbids Land",
	"Rabbids Rumble",
	"Rabbids Wild Race",
	"Rabbids: Coding!",
	"Rabbids: Party of Legends",
	"Rabbids: Travel in Time 3D",
	"Racquet Sports",
	"Rally Championship 2002",
	"Ranx: The Video Game",
	"Raving Rabbids: Alive & Kicking",
	"Raving Rabbids: Travel in Time",
	"Rayman",
	"Rayman 2 Forever",
	"Rayman 2: The Great Escape",
	"Rayman 3",
	"Rayman 3 HD",
	"Rayman 3: Hoodlum Havoc",
	"Rayman 3D",
	"Rayman Advance",
	"Rayman Adventures",
	"Rayman Arena",
	"Rayman Designer",
	"Rayman DS",
	"Rayman Fiesta Run",
	"Rayman Jungle Run",
	"Rayman Legends",
	"Rayman Legends: Definitive Edition",
	"Rayman Mini",
	"Rayman Origins",
	"Rayman Raving Rabbids",
	"Rayman Raving Rabbids 2",
	"Rayman Raving Rabbids: TV Party",
	"Rayman Revolution",
	"Rayman Rush",
	"Rayman: Hoodlum's Revenge",
	"Real Football 2008 3D",
	"Red Steel",
	"Red Steel 2",
	"Redline Racer",
	"Requiem: Avenging Angel",
	"Resident Evil 4",
	"Riders Republic",
	"Riding Champion: Legacy of Rosemond Hill",
	"Risk",
	"Risk: Urban Assault",
	"Rock Gods: Tap Tour",
	"Rocket: Robot on Wheels",
	"Rocksmith",
	"Rocksmith: All-new 2014 Edition",
	"Rocksmith: All-new 2014 Edition - Remastered",
	"Rocksmith+",
	"Rocky",
	"Rocky Balboa",
	"Rocky Legends",
	"Roller Champions",
	"Roswell Conspiracies: Aliens, Myths & Legends",
	"RS3: Racing Simulation Three",
	"Rugby Challenge 2006",
	"S.C.A.R.S.",
	"Sabrina, the Teenage Witch: Potion Commotion",
	"Saddle Up: Time to Ride",
	"Safari Photo Africa: Wild Earth",
	"Salt Lake 2002",
	"Sandstorm: Pirate Wars",
	"Scott Pilgrim vs. the World: The Game",
	"Scott Pilgrim vs. The World: The Game - Complete Edition",
	"Scrabble",
	"Scrabble 2007 Edition",
	"Scrabble: 2003 Edition",
	"Sea Dogs",
	"Sean Dundee's World Club Football",
	"Secrets of the Luxor",
	"Self-Defense Training Camp",
	"Seven Kingdoms II: The Fryhtan Wars",
	"Shadow Company: Left for Dead",
	"Shadow Gunner: The Robot Wars",
	"Shadowbane",
	"Shape Up",
	"Shape Up: Battle Run",
	"Shaun White Skateboarding",
	"Shaun White Snowboarding",
	"Shaun White Snowboarding: Road Trip",
	"Shaun White Snowboarding: World Stage",
	"Sherlock Holmes: The Case of the Silver Earring",
	"Shoot Many Robots",
	"ShootMania Storm",
	"Silent Hunter 5: Battle of the Atlantic",
	"Silent Hunter II",
	"Silent Hunter III",
	"Silent Hunter: Wolves of the Pacific",
	"Six Flags Fun Park",
	"Skateball",
	"Skull & Bones",
	"Skullcaps",
	"Sleepover Party",
	"Sno-Cross Championship Racing",
	"Soul Blazer",
	"South Park: Phone Destroyer",
	"South Park: The Fractured But Whole",
	"South Park: The Stick of Truth",
	"Space Junkies",
	"Spartacus Legends",
	"Speed Busters: American Highways",
	"Speed Challenge: Jacques Villeneuve's Racing Vision",
	"Speed Devils",
	"Spirou: The Robot Invasion",
	"Splinter Cell: Blacklist - Spider-Bot",
	"Sports Collection: 15 Sports to Master",
	"Sports Party",
	"Sprung",
	"ST Krak",
	"Star Trek: Bridge Crew",
	"Star Wars",
	"Star Wars Trilogy: Apprentice of the Force",
	"Star Wars: Episode I - Racer",
	"Star Wars: Episode III - Revenge of the Sith",
	"Star Wars: Lethal Alliance",
	"Star Wars: The Empire Strikes Back",
	"Starlink: Battle for Atlas",
	"Starush",
	"Steep",
	"Stratego: Next Edition",
	"Street Fighter Alpha 3",
	"Street Racer",
	"Street Riders",
	"Stupid Invaders",
	"Style Lab: Jewelry Design",
	"Style Lab: Makeover",
	"Sub Culture",
	"Sunny Garcia Surfing",
	"Super Bust-A-Move",
	"Super Bust-A-Move 2",
	"Super Street Fighter II: Turbo Revival",
	"Surf Riders",
	"Surf's Up",
	"Suzuki Alstare Extreme Racing",
	"Sven-Göran Eriksson's World Challenge",
	"Sven-Göran Eriksson's World Manager",
	"Sword of the Samurai",
	"Taxi 2",
	"Taxi 3",
	"Teenage Mutant Ninja Turtles",
	"Teenage Mutant Ninja Turtles: Arcade Attack",
	"Teenage Mutant Ninja Turtles: Smash-Up",
	"Teenage Mutant Ninja Turtles: Turtles in Time Re-Shelled",
	"Telly Addicts",
	"Tenchu: Shadow Assassins",
	"Tetris Ultimate",
	"The $1,000,000 Pyramid",
	"The Adventures of Tintin: The Secret of the Unicorn",
	"The Adventures of Valdo & Marie",
	"The Avengers: Battle for Earth",
	"The Bard's Tale",
	"The Black Eyed Peas Experience",
	"The Crew",
	"The Crew 2",
	"The Dog Island",
	"The Dukes of Hazzard: Return of the General Lee",
	"The Elder Scrolls III: Morrowind",
	"The Elder Scrolls IV: Oblivion",
	"The Expendables 2: Videogame",
	"The Fifth Element",
	"The Final Cut",
	"The Hip Hop Dance Experience",
	"The Hollywood Squares",
	"The Koshan Conspiracy",
	"The Legend of Alon D'ar",
	"The Longest Journey",
	"The Mask of Zorro",
	"The Mighty Quest for Epic Loot",
	"The Mummy",
	"The Perfect General",
	"The Political Machine",
	"The Price Is Right",
	"The Price is Right: 2010 Edition",
	"The Price is Right: Decades",
	"The Settlers",
	"The Settlers 7: Paths to a Kingdom",
	"The Settlers II: 10th Anniversary",
	"The Settlers IV",
	"The Settlers Online",
	"The Settlers: History Edition",
	"The Settlers: Rise of an Empire",
	"The Settlers: Rise of Cultures",
	"The Smurfs",
	"The Smurfs & Co",
	"The Smurfs & Co: Spellbound",
	"The Smurfs 2",
	"The Smurfs 3D",
	"The Smurfs Dance Party",
	"The Smurfs: Epic Run",
	"The Sum of All Fears",
	"Theocracy",
	"Tiger Woods PGA Tour Golf",
	"TMNT",
	"TOCA: World Touring Cars",
	"Tokyo Xtreme Racer 2",
	"Tokyo Xtreme Racer: Zero",
	"Tom and Jerry in Fists of Furry",
	"Tom and the Ghost",
	"Tom Clancy's Elite Squad",
	"Tom Clancy's EndWar",
	"Tom Clancy's EndWar Online",
	"Tom Clancy's Ghost Recon",
	"Tom Clancy's Ghost Recon 2",
	"Tom Clancy's Ghost Recon 2: Summit Strike",
	"Tom Clancy's Ghost Recon Advanced Warfighter",
	"Tom Clancy's Ghost Recon Advanced Warfighter 2",
	"Tom Clancy's Ghost Recon Breakpoint",
	"Tom Clancy's Ghost Recon Phantoms",
	"Tom Clancy's Ghost Recon Predator",
	"Tom Clancy's Ghost Recon Wildlands",
	"Tom Clancy's Ghost Recon: Desert Siege",
	"Tom Clancy's Ghost Recon: Future Soldier",
	"Tom Clancy's Ghost Recon: Island Thunder",
	"Tom Clancy's Ghost Recon: Jungle Storm",
	"Tom Clancy's Ghost Recon: Shadow Wars",
	"Tom Clancy's H.A.W.X",
	"Tom Clancy's H.A.W.X 2",
	"Tom Clancy's Rainbow Six 3",
	"Tom Clancy's Rainbow Six 3: Athena Sword",
	"Tom Clancy's Rainbow Six 3: Black Arrow",
	"Tom Clancy's Rainbow Six 3: Raven Shield",
	"Tom Clancy's Rainbow Six Extraction",
	"Tom Clancy's Rainbow Six Mobile",
	"Tom Clancy's Rainbow Six Siege",
	"Tom Clancy's Rainbow Six Vegas",
	"Tom Clancy's Rainbow Six Vegas 2",
	"Tom Clancy's Rainbow Six: Critical Hour",
	"Tom Clancy's Rainbow Six: Lockdown",
	"Tom Clancy's Rainbow Six: Lone Wolf",
	"Tom Clancy's Rainbow Six: Rogue Spear",
	"Tom Clancy's Rainbow Six: Rogue Spear - Black Thorn",
	"Tom Clancy's Rainbow Six: Rogue Spear Mission Pack - Urban Operations",
	"Tom Clancy's Splinter Cell",
	"Tom Clancy's Splinter Cell 3D",
	"Tom Clancy's Splinter Cell Classic Trilogy HD",
	"Tom Clancy's Splinter Cell HD",
	"Tom Clancy's Splinter Cell: Blacklist",
	"Tom Clancy's Splinter Cell: Chaos Theory",
	"Tom Clancy's Splinter Cell: Chaos Theory HD",
	"Tom Clancy's Splinter Cell: Conviction",
	"Tom Clancy's Splinter Cell: Double Agent",
	"Tom Clancy's Splinter Cell: Essentials",
	"Tom Clancy's Splinter Cell: Pandora Tomorrow",
	"Tom Clancy's Splinter Cell: Pandora Tomorrow HD",
	"Tom Clancy's The Division",
	"Tom Clancy's The Division 2",
	"Tom Clancy's The Division Heartland",
	"Tom Clancy's The Division Resurgence",
	"Tomb Raider: The Prophecy",
	"Tonic Trouble",
	"Toonsylvania",
	"Top Trumps Adventures!",
	"Top Trumps: Dogs & Dinosaurs",
	"Top Trumps: Horror & Predators",
	"Tork: Prehistoric Punk",
	"Totally Spies! 3: Secret Agents",
	"Toy Soldiers: War Chest",
	"TrackMania",
	"TrackMania 2: Canyon",
	"TrackMania 2: Lagoon",
	"TrackMania 2: Stadium",
	"TrackMania 2: Valley",
	"TrackMania Turbo",
	"Trains & Trucks Tycoon",
	"Transference",
	"Trevor Chan's Capitalism II",
	"Trials Evolution",
	"Trials Evolution: Gold Edition",
	"Trials Frontier",
	"Trials Fusion",
	"Trials of the Blood Dragon",
	"Trials Rising",
	"Trivial Pursuit",
	"Trivial Pursuit Live!",
	"Trivial Pursuit Live! 2",
	"Trollz: Hair Affair!",
	"TwinWorld: Land of Vision",
	"UFC: Throwdown",
	"Ultimate Fighting Championship: Tapout",
	"Uno",
	"Unreal",
	"Uru: Ages Beyond Myst",
	"V.I.P.",
	"Vacation Sports",
	"Valiant Hearts: The Great War",
	"Virtual Skipper",
	"Voodoo Dice",
	"Vroom",
	"Wall Street Tycoon",
	"Walt Disney's Snow White and the Seven Dwarfs",
	"Walt Disney's The Jungle Book: Mowgli's Wild Adventure",
	"Walt Disney's The Jungle Book: Rhythm n' Groove",
	"Warlords IV: Heroes of Etheria",
	"Warlords: Battlecry II",
	"WarTech: Senko no Ronde",
	"Watch Dogs",
	"Watch Dogs 2",
	"Watch Dogs: Legion",
	"We Dare",
	"Werewolves Within",
	"Wheel of Fortune",
	"Wheelman",
	"Where's Waldo? The Fantastic Journey",
	"Who Wants to Be a Millionaire: 1st Edition",
	"Who Wants to Be a Millionaire: 2nd Edition",
	"Wild Arms 3",
	"Will Rock",
	"Wizardry: Tale of the Forsaken Land",
	"World Football 98",
	"World in Conflict: Soviet Assault",
	"Worms Blast",
	"Worms World Party",
	"X-Bladez: Inline Skater",
	"XDefiant",
	"XIII",
	"Your Shape",
	"Your Shape: Fitness Evolved 2012",
	"Your Shape: Fitness Evolved 2013",
	"Zeit²",
	"Zombi",
	"ZombiU",
	"Zoo Mania 3D",
}
