name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v -o u2ug .

    - name: Build wasm
      run: GOOS=js GOARCH=wasm go build -v -o u2ug.wasm .