name: Release JS WASM

on:
  release:
    types: [created]

jobs:
  release-js-wasm:
    name: release js/wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: js
          goarch: wasm
          binary_name: u2ug.wasm